import type { Metadata } from "next";
import { Pixelify_Sans  } from "next/font/google";
import Header from "@/components/Header/Header";

import PageTransition from "@/components/PageTransition/PageTransition";

import './globals.css'
import Footer from "@/components/Footer/Footer";

const pixel = Pixelify_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${pixel.className}`}
      >
        <Header/>
        <PageTransition>
        {children}
        </PageTransition>

      <Footer/>
      </body>
    </html>
  );
}
